{
 "title": "Telemetry",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Connected Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "waku_connected_peers" }
   ]
  },
  {
   "title": "Network Rate (MBps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "waku_network_rate{type=\"relay\"} / 1000000"
    }
   ]
  },
  {
   "title": "Total Bandwidth (MBps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(irate(waku_network_bytes{type=\"relay\", direction=\"out\"}[1m])) / 1000000"
    },
    {
     "expr": "sum(irate(waku_network_bytes{type=\"relay\", direction=\"in\"}[1m])) / 1000000"
    }
   ]
  },
  {
   "title": "Envelopes Validated Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "irate(waku2_envelopes_validated_total[1m])"
    }
   ]
  }
 ]
}