name: tests

on:
  pull_request:
  push:
    branches:
      - master


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: tests
      run: make test
